### ISSUE TITLE
Several Bugs during todays presentation

### ISSUE THREAD

**Issue by bytschkow** [SES-fortiss/SmartGridCoSimulation#165]
- [ ]  memap.helper.profilehandler.TimedDataHandler.handleProfiles(TimedDataHandler.java:59) WARNING: some data intervals is missing data! The inteval value is set to 0.0
this error is thrown, when a consumption file ends with an empy line

- [x]  if consumption is left empty with string ' ', there is an error here
`java.io.FileNotFoundException: 
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at memap.helper.FileManager.readFromSource(FileManager.java:46)
	at memap.helper.FileManager.getBuffer(FileManager.java:66)
	at memap.components.CSVConsumer.setProfiles(CSVConsumer.java:112)
	at memap.components.CSVConsumer.<init>(CSVConsumer.java:37)
	at memap.controller.GuiController$CSVConsumerDeserializer.deserialize(GuiController.java:386)`
- [ ]  error handling due to that error, gives another error: 
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at simulation.SimulationStarter.stopSimulationStatic(SimulationStarter.java:177)
	at memap.components.CSVConsumer.setProfiles(CSVConsumer.java:130)
	at memap.components.CSVConsumer.<init>(CSVConsumer.java:37)
	at memap.controller.GuiController$CSVConsumerDeserializer.deserialize(GuiController.java:390)`

**Comment by bytschkow** [comment]
> 
> 
>     * [ ]   memap.helper.profilehandler.TimedDataHandler.handleProfiles(TimedDataHandler.java:59) WARNING: some data intervals is missing data! The inteval value is set to 0.0
>       this error is thrown, when a consumption file ends with an empy line
> 

this is adressed by executed pull-request #164 
>     * [x]   if consumption is left empty with string ' ', there is an error here
>       `java.io.FileNotFoundException:  at java.io.FileInputStream.open0(Native Method) at java.io.FileInputStream.open(Unknown Source) at java.io.FileInputStream.<init>(Unknown Source) at java.io.FileInputStream.<init>(Unknown Source) at java.io.FileReader.<init>(Unknown Source) at memap.helper.FileManager.readFromSource(FileManager.java:46) at memap.helper.FileManager.getBuffer(FileManager.java:66) at memap.components.CSVConsumer.setProfiles(CSVConsumer.java:112) at memap.components.CSVConsumer.<init>(CSVConsumer.java:37) at memap.controller.GuiController$CSVConsumerDeserializer.deserialize(GuiController.java:386)`
> 
>     * [ ]   error handling due to that error, gives another error:
>       `Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException at simulation.SimulationStarter.stopSimulationStatic(SimulationStarter.java:177) at memap.components.CSVConsumer.setProfiles(CSVConsumer.java:130) at memap.components.CSVConsumer.<init>(CSVConsumer.java:37) at memap.controller.GuiController$CSVConsumerDeserializer.deserialize(GuiController.java:390)`

**Comment by bytschkow** [comment]
In the meantime, these bugs are not observed anymore. Closing this issue then.
